### ISSUE TITLE
API V3

### ISSUE THREAD

**Issue by drkorobov** [Hopex-Development/yandex#1]
Hi! Excelent project but new voices unavailable. Can you add V3 support?

**Comment by H0pex** [comment]
> Hi! Excelent project but new voices unavailable. Can you add V3 support?

Thank you for your interest! Do you mean the [extended list of voices](https://cloud.yandex.ru/en/docs/speechkit/tts/voices) from v3?

**Comment by drkorobov** [comment]
> > Hi! Excelent project but new voices unavailable. Can you add V3 support?
> 
> Thank you for your interest! Do you mean the [extended list of voices](https://cloud.yandex.ru/en/docs/speechkit/tts/voices) from v3?

Yes, new voices from V3
https://cloud.yandex.ru/en/docs/speechkit/tts-v3/api-ref/grpc/
sample ( not С#) ///// convert to new Speech2.cs
https://cloud.yandex.ru/en/docs/speechkit/tts/api/tts-examples-v3

**Comment by drkorobov** [comment]
Hmm...
You can't simple add voice in list- it don't work.
I tried new voices kirill and masha (ru-RU) - and
![2024-01-28_163042](https://github.com/Hopex-Development/yandex/assets/48697430/87856cc9-05c9-401e-9ccd-3e73c0c83442)
 nothing.
 `string request = "https://tts.voicetech.yandex.net/generate?" + $@"key={key}&text={text}&speaker={speaker.ToString().ToLower()}&emotion={emotion.ToString().ToLower()}&speed={speed}&format=mp3&lang={lang}";`

need another API - API V3
`channel = grpc.secure_channel('tts.api.cloud.yandex.net:443', cred)`
